version: '3'
services: 
    db:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=newspage
            - MYSQL_ROOT_PASSWORD=pass1234
    newspage:
        build: .
        command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate"
        environment: 
            - DB_USER=root
            - DB_PASSWORD=pass1234
        links:
            - db
        ports:
            - "5050:8000"
        depends_on: 
            - db
    admin:
        image: phpmyadmin/phpmyadmin
        ports: 
            - "5060:80"
        links: 
            - db