# Generated by Django 2.2.3 on 2019-07-16 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.TextField(help_text='Enter the topic of articles')),
                ('url', models.TextField(help_text='Enter URL of topic RSS Feed')),
            ],
        ),
        migrations.CreateModel(
            name='MainSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter name of main site')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_period', models.IntegerField(help_text='Enter number of days from which to show articles')),
                ('articles_per_page', models.IntegerField(help_text='Enter number of articles displayed per page')),
                ('following_sites', models.ManyToManyField(help_text='Select sites to follow', to='newspage.FeedList')),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feedlist',
            name='main_site',
            field=models.ForeignKey(help_text='Enter the URL of the Main Site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspage.MainSite'),
        ),
    ]
