# Generated by Django 2.2.3 on 2019-07-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlist',
            name='topic_name',
            field=models.CharField(help_text='Enter the topic of articles', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedlist',
            name='url',
            field=models.CharField(help_text='Enter URL of topic RSS Feed', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='name',
            field=models.CharField(help_text='Enter name of main site', max_length=100),
        ),
    ]
